language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly
    - php: nightly

before_script:
  - composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - wget https://phar.phpunit.de/phploc.phar
  - chmod +x phploc.phar

script:
  - vendor/bin/phpunit
  - php phploc.phar --log-xml build/phploc.xml src
